#!/bin/bash

# Exit immediately on errors, and echo commands as they are executed.
set -ex

# Set the $PATH to include the global composer bin directory.
PATH=$PATH:~/.composer/vendor/bin

# Log in and create a new environment for this test.
terminus auth login --machine-token=$TERMINUS_TOKEN
terminus site create-env --to-env=$TERMINUS_ENV --from-env=dev

# Somehow the remote might already be there.
git remote show | grep -q pantheon || git remote add pantheon $(terminus site connection-info --field=git_url)
git fetch pantheon
git checkout -b $TERMINUS_ENV
git push pantheon $TERMINUS_ENV -f

# We have to wait for the code converge to finish before setting sftp mode. Maybe.
sleep 60
terminus site set-connection-mode --mode=sftp
